---
title: "Ukraine War: Russian Losses"
author: "Cormac Nolan"
date: "3/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(forecast)
```

## Import

```{r cars}
russian_losses <- tibble::tribble(
  ~report_date, ~soldiers, ~planes, ~helicopters, ~tanks,  ~artillery_pieces,  
  ~armoured_personell_carriers, ~mlrs, ~boats, ~vehicles, ~fuel_tankers, ~uav, ~aa_systems,
  "2022-02-23", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  "2022-02-26", 3500, 14, 8, 102, 15, 536, 1, 0, 0, 0, 0, 0,
  "2022-02-28", 3500, 29, 29, 191, 74, 816, 22, 0, 291, 60, 3, 5,
  "2022-03-01", 5710, 29, 29, 198, 77, 846, 24, 2, 305, 60, 3, 7,
  "2022-03-02", 5840, 30, 31, 211, 85, 862, 40, 2, 355, 60, 3, 9,
  "2022-03-06", 11000, 44, 48, 285, 109, 985, 50, 2, 447, 60, 4, 21,
  "2022-03-07", 11000, 46, 68, 290, 117, 999, 50, 2, 454, 60, 7, 23,
  "2022-03-08", 12000, 48, 80, 303, 120, 1036, 56, 2, 474, 60, 7, 27,
  "2022-03-10", 12000, 49, 81, 335, 123, 1105, 56, 2, 526, 60, 7, 29,
  "2022-03-11", 12000, 57, 83, 353, 125, 1165, 58, 2, 558, 60, 7, 31,
  "2022-03-16", 13800, 84, 108, 430, 190, 1375, 70, 2, 819, 60, 11, 43,
  "2022-03-17", 14000, 86, 108, 444, 201, 1435, 72, 2, 864, 60, 11, 43,
  "2022-03-18", 14200, 93, 112, 450, 205, 1448, 72, 3, 879, 60, 12, 43,
  "2022-03-19", 14400, 95, 115, 466, 213, 1470, 72, 3, 914, 60, 17, 44,
  "2022-03-24", 15800, 108, 124, 530, 280, 1597, 82, 4, 1033, 72, 50, 47,
  "2022-03-25", 16100, 115, 125, 561, 291, 1625, 90, 5, 1089, 72, 53, 50,
  "2022-03-26", 16400, 117, 127, 575, 293, 1640, 91, 7, 1131, 73, 56, 51,
  "2022-03-27", 16600, 121, 127, 582, 294, 1664, 93, 7, 1144, 73, 56, 52,
  "2022-03-28", 17000, 123, 127, 586, 302, 1694, 95, 7, 1150, 73, 66, 54,
  "2022-03-29", 17200, 127, 129, 597, 303, 1710, 96, 7, 1178, 73, 71, 54,
  ) %>% 
  mutate(report_date = as.Date(report_date))

campaign_length = as.integer(max(russian_losses$report_date) - min(russian_losses$report_date))
campaign_length_weeks = ceiling(campaign_length / 7)

russian_losses
 
```

## Exploration

```{r pressure, echo=FALSE}
 
russian_losses %>% 
  filter(report_date == as.character(max(russian_losses$report_date))) %>% 
  select(-report_date) %>% 
  purrr::map_df(.f=function(x) x / campaign_length)
```

```{r, fig.height=7}
russian_losses %>% 
  select(report_date, tanks, artillery_pieces, armoured_personell_carriers, vehicles) %>% 
  tidyr::pivot_longer(cols = where(~is.numeric(.x)), names_to="loss_type", values_to="loss_value") %>% 
  ggplot(aes(report_date, loss_value, group=loss_type, colour=loss_type)) +
  geom_line() +
  facet_wrap(~loss_type, ncol = 2)

```


```{r, fig.height=7}
russian_losses %>% 
  select(report_date, soldiers, armoured_personell_carriers, vehicles) %>% 
  tidyr::pivot_longer(cols = where(~is.numeric(.x)), names_to="loss_type", values_to="loss_value") %>% 
  ggplot(aes(report_date, loss_value, group=loss_type, colour=loss_type)) +
  geom_line() +
  facet_wrap(~loss_type, ncol = 3)

```

```{r, fig.height=7}
russian_losses %>% 
  select(report_date, planes, helicopters, artillery_pieces, mlrs, aa_systems) %>% 
  tidyr::pivot_longer(cols = where(~is.numeric(.x)), names_to="loss_type", values_to="loss_value") %>% 
  ggplot(aes(report_date, loss_value, group=loss_type, colour=loss_type)) +
  geom_line() +
  facet_wrap(~loss_type, ncol = 2)

```



## Rates

First we need to apply interpolation, linear is fine for now.

```{r, fig.height=7}

russian_losses_all_dates <-
  dplyr::tibble(report_date = min(russian_losses$report_date) + 0:campaign_length) %>%
  left_join(russian_losses, by="report_date")


russian_losses_all_dates
```


```{r, fig.height=7}
russian_losses_all_dates <- 
  russian_losses_all_dates %>% 
  mutate(across(where(~is.numeric(.x)), .fns=forecast::na.interp)) %>%
  mutate(across(where(~is.numeric(.x)), .fns=as.numeric)) %>% 
  mutate(across(where(~is.numeric(.x)), .fns=round))

russian_losses_all_dates
```

```{r}
russian_losses_all_dates <- 
  russian_losses_all_dates %>% 
  mutate(campaign_week_number = c(0, rep(1:campaign_length_weeks, each=7)[1:(campaign_length)]))
  
russian_losses_all_dates
```


```{r}
daily_diff <- function(val){
  val - dplyr::lag(val) 
}

rate_plot <- function(df, loss_column){
  .loss_column = enquo(loss_column)
  
  df %>% 
    select(report_date, {{loss_column}}, campaign_week_number) %>% 
    mutate(across(where(~is.numeric(.x)), .fns=daily_diff)) %>% 
    tidyr::drop_na() %>% 
    ggplot(aes(report_date, {{loss_column}})) +
    geom_smooth(se=FALSE, span=0.5) +
    geom_bar(stat = "identity", alpha = 0.3) +
    labs(title = quo_name(.loss_column))
}


rate_plot(russian_losses_all_dates, soldiers)
  

```


```{r}

rate_plot(russian_losses_all_dates, vehicles)

```


```{r}

rate_plot(russian_losses_all_dates, tanks)

```

```{r}

rate_plot(russian_losses_all_dates, armoured_personell_carriers)

```

```{r, fig.height=7}
rate_plot(russian_losses_all_dates, artillery_pieces)

```

```{r, fig.height=7}
rate_plot(russian_losses_all_dates, planes)

```

```{r, fig.height=7}
rate_plot(russian_losses_all_dates, uav)

```

```{r, fig.height=7}
rate_plot(russian_losses_all_dates, helicopters)

```

